#!/bin/bash

echo "Welcome to ohmyheart project"
echo "Enter password to continue"
echo "> "

read PASW

if [ "${PASW}" != "5555" ]; then
  echo "Wrong password!"
  sleep 10;
  exit 1;
fi;

while true; do
  echo "MENU: available commands";
  echo "  b1 <N> - brightness for hrm chan 1 [0-99]"
  echo "  b2 <N> - brightness for hrm chan 2 [0-99]"
  echo "  ba <N> - brightness for chan a [0-99]"
  echo "  bb <N> - brightness for chan b [0-99]"
  echo "  bi <N> - idle brightness [0-99]"
  echo "  pi <N> - idle pulse (default: 20 bpm = 1pulse/3seconds) "
  echo "Set chan modes: 0=hrm/idle, 1=idle, 2=hrm/off, 3=off, 4=on"
  echo "  ma <n> - mode for channel a"
  echo "  mb <n> - mode for channel b"
  echo "  wifi <ssid> <pass> - setup wifi internet access"
  echo "  off - set all brightness to zero"
  echo "  on - set brightness to 25%"
  echo "  st - status"
  echo "  reset - reset all settings to factory defaults"
  echo "  re - reboot"

  echo -n "> ";
  read ROW;
  
  PARAMS=($ROW)
  CMD="${PARAMS[0]}"

  case "${CMD}" in
	wifi)
		SSID="${PARAMS[1]}"
		PASS="${PARAMS[2]}"
		echo setup ssid=${SSID}
		
		WPA="/etc/wpa_supplicant/wpa_supplicant.conf"
		echo "country=RU" >$WPA
		echo "ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev" >>$WPA
		echo "update_config=1" >>$WPA
		echo "network={" >>$WPA
		echo "  ssid=\"${SSID}\"" >>$WPA
		echo "  psk=\"${PASS}\"" >>$WPA
		echo "  priority=5" >>$WPA
		echo "}" >>$WPA
		
		service wpa_supplicant restart		
		;;
	st)
		service hrmon status
		service dimmer status
		echo
		echo "--- redis keys: ---"
		for KEY in `redis-cli --raw keys \*`; do
		  echo $KEY `redis-cli --raw get "$KEY"`;
		done;
		echo
		echo "--- route status: ---"
		ip ro
		;;
	b1)
		VAL=$(( ${PARAMS[1]} * 255 / 99 ))
		if [ $(( $VAL + 1 )) -le 255 ]; then
		  redis-cli set bright.1 $VAL;
		fi;
		;;
	b2)
		VAL=$(( ${PARAMS[1]} * 255 / 99 ))
		if [ $(( $VAL + 1 )) -le 255 ]; then
		  redis-cli set bright.2 $VAL;
		fi;
		;;
	ba)
		VAL=$(( ${PARAMS[1]} * 255 / 99 ))
		if [ $(( $VAL + 1 )) -le 256 ]; then
		  redis-cli set bright.a $VAL;
		fi;
		;;
	bb)
		VAL=$(( ${PARAMS[1]} * 255 / 99 ))
		if [ $(( $VAL + 1 )) -le 256 ]; then
		  redis-cli set bright.b $VAL;
		fi;
		;;
	bi)
		VAL=$(( ${PARAMS[1]} * 255 / 99 ))
		if [ $(( $VAL + 1 )) -le 256 ]; then
		  redis-cli set bright.idle $VAL;
		fi;
		;;
	pi)
		VAL="${PARAMS[1]}"
		if [ $(( $VAL + 1 )) -le 200 ]; then
		  redis-cli set pulse.idle $VAL;
		fi;
		;;
	ma)
		VAL="${PARAMS[1]}"
		if [ $(( $VAL + 1 )) -le 200 ]; then
		  redis-cli set mode.a $VAL;
		fi;
		;;
	mb)
		VAL="${PARAMS[1]}"
		if [ $(( $VAL + 1 )) -le 200 ]; then
		  redis-cli set mode.b $VAL;
		fi;
		;;
	off)
		redis-cli set bright.1 0;
		redis-cli set bright.2 0;
		redis-cli set bright.idle 0;
		redis-cli set bright.a 0;
		redis-cli set bright.b 0;
		;;
	on)
		redis-cli set bright.1 255;
		redis-cli set bright.2 255;
		redis-cli set bright.a 255;
		redis-cli set bright.b 255;
		redis-cli set bright.idle 255;
		;;
	reset)
		redis-cli set bright.1 255;
		redis-cli set bright.2 255;
		redis-cli set bright.a 255;
		redis-cli set bright.b 255;
		redis-cli set bright.idle 255;

		redis-cli set mode.a 0;
		redis-cli set mode.b 0;
		redis-cli set pulse.idle 24;
		;;
	re)
		reboot
		;;		

	*)
		echo "Unknown command: $CMD"
		;;

  esac
done;